// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/react/react-global.d.ts
import React = __React;
import ReactDOM = __React.__DOM;

// No idea why the below namespace doesn't work, but these definitions files don't affect semantics. If there are no compiler errors, it's fine.

//declare namespace __React {
//    export import addons = __React.__Addons;
//}
